pipeline {
    agent any

    parameters {
        choice(choices:["Test", "Dev", "QA", "PRE-PROD", "PROD"], description:"Options ", name: "deployEnv")
    }

    stages {
        stage("Demo"){
            steps {
                echo "String is set to: ${params.deployEnv}"
            }
        }
    }
    
}
